// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "EchoVision",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "EchoVision",
            targets: ["AppModule"],
            bundleIdentifier: "com.hals.EchoVision",
            teamIdentifier: "YRV6Y22NVW",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown
            ],
            capabilities: [
                .camera(purposeString: "EchoVision uses the camera to detect objects, hazards, and help you navigate your surroundings safely."),
                .microphone(purposeString: "EchoVision uses the microphone for spatial audio feedback and voice announcements.")
            ],
            appCategory: "public.app-category.navigation"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Assets.xcassets"),
                .copy("Resources/HazardDetector.mlmodelc"),
                .copy("Resources/IndoorObstaclesDetector.mlmodelc"),
                .copy("Resources/PersonalObjectClassifier.mlmodelc"),
                .copy("Resources/SceneClassifier.mlmodelc"),
                .copy("Resources/yolov8n.mlmodelc")
            ]
        )
    ]
)
